language: python
dist: focal
python:
  - 3.8
install:
  # Install nix:
  - sh <(curl -L https://nixos.org/nix/install) --daemon --yes
  # Test nix-build:
  - source /etc/profile.d/nix.sh
  - printenv
  - nix-build '<nixpkgs>' -A hello
  # Install python requirements:
  - pip3 install -r requirements.txt
script:
  - make pre-push